services:
  - type: web
    name: og-appan-game-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: OWNER_ID
        value: "1445101801304227922"
